# Generated by Django 4.2 on 2025-02-12 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=100, unique=True)),
                ('category_name', models.CharField(max_length=255)),
                ('inserted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemeCoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inserted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemeCoinCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_categories', to='trading_bot.categories')),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_categories', to='trading_bot.memecoins')),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('market_cap', models.BigIntegerField()),
                ('total_volume', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('price_change_1h', models.FloatField()),
                ('price_change_24h', models.FloatField()),
                ('liquidity_score', models.FloatField(blank=True, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='trading_bot.memecoins')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
