# Generated by Django 4.2 on 2025-02-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketdata',
            options={'ordering': ['-last_updated']},
        ),
        migrations.RenameField(
            model_name='marketdata',
            old_name='total_volume',
            new_name='circulating_supply',
        ),
        migrations.RenameField(
            model_name='marketdata',
            old_name='coin',
            new_name='coin_id',
        ),
        migrations.RenameField(
            model_name='marketdata',
            old_name='timestamp',
            new_name='inserted_at',
        ),
        migrations.RenameField(
            model_name='memecoins',
            old_name='created_at',
            new_name='coin_creation_date',
        ),
        migrations.RemoveField(
            model_name='marketdata',
            name='price_change_1h',
        ),
        migrations.RemoveField(
            model_name='marketdata',
            name='price_change_24h',
        ),
        migrations.RemoveField(
            model_name='memecoins',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='memecoins',
            name='name',
        ),
        migrations.AddField(
            model_name='marketdata',
            name='bid_ask_spread',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='conversion_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='conversion_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='high_24h',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='last_volume_base',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='last_volume_quote',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='low_24h',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='market',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='market_cap_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='open_24h',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='price_change_percentage_1h',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='price_change_percentage_24h',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='price_change_percentage_7d',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='total_supply',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='volume_24h_base',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='volume_24h_quote',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='memecoins',
            name='coin_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='memecoins',
            name='coin_full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memecoins',
            name='coin_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memecoins',
            name='coin_symbol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='memecoins',
            name='total_coins_milled',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='liquidity_score',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='market_cap',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='memecoins',
            name='coin_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['-last_updated'], name='trading_bot_last_up_4368f8_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['market_cap'], name='trading_bot_market__a17286_idx'),
        ),
        migrations.AddIndex(
            model_name='marketdata',
            index=models.Index(fields=['price_change_percentage_24h'], name='trading_bot_price_c_d9aa92_idx'),
        ),
    ]
