# Generated by Django 4.2 on 2025-02-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0002_alter_marketdata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memecoins',
            old_name='total_coins_milled',
            new_name='total_coins_mined',
        ),
    ]
