# Generated by Django 4.2 on 2025-02-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0003_rename_total_coins_milled_memecoins_total_coins_mined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memecoins',
            name='coin_creation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
