# Generated by Django 4.2 on 2025-02-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0004_alter_memecoins_coin_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketdata',
            name='coin_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
