# Generated by Django 4.2 on 2025-02-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0006_alter_marketdata_coin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('coin_id', models.CharField(default='SOL', max_length=10)),
                ('trade_type', models.CharField(max_length=4, null=True)),
                ('status', models.CharField(default='OPEN', max_length=6, null=True)),
                ('buying_price', models.DecimalField(decimal_places=15, max_digits=30)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('quantity', models.DecimalField(decimal_places=15, max_digits=30)),
                ('total_paid_amount', models.DecimalField(decimal_places=15, max_digits=30)),
                ('total_received_amount', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('buy_date', models.DateTimeField(auto_now_add=True)),
                ('sell_date', models.DateTimeField(blank=True, null=True)),
                ('tx_hash', models.CharField(max_length=100, unique=True)),
                ('wallet_address', models.CharField(max_length=44)),
                ('token_address', models.CharField(default='So11111111111111111111111111111111111111112', max_length=44)),
            ],
        ),
    ]
